[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# https://updraft.cyfrin.io/courses/security/review/upgradeable-contracts?lesson_format=transcript 
[fuzz]
runs = 256
max_test_rejects = 65536
seed = "0x3e8"
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# https://updraft.cyfrin.io/courses/security/review/installing-libraries?lesson_format=transcript 
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
