[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# viaIR = true
# optimizer = true
# optimizer_runs = 200
# revert_strings = "strip"

# https://updraft.cyfrin.io/courses/security/review/installing-libraries?lesson_format=transcript 
remappings = ['@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/', '@uniswap/v2-core/contracts/=lib/v2-core/contracts/', '@uniswap/v2-periphery/contracts/=lib/v2-periphery/contracts/','@uniswap/lib/contracts/=lib/solidity-lib/contracts/', 'solmate/=lib/solmate/', '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/']
# to test the uniswap contracts, turn on the following line (https://github.com/aurelien-cuvelier/local-uniswapv2-foundry/blob/master/foundry.toml)
unchecked_cheatcode_artifacts = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# https://updraft.cyfrin.io/courses/security/review/upgradeable-contracts?lesson_format=transcript 
[fuzz]
runs = 256
max_test_rejects = 65536
seed = "0x3e8"
dictionary_weight = 40
include_storage = true
include_push_bytes = true




